### ISSUE TITLE
What is the ownership status of the project?

### ISSUE THREAD

**Issue by codeworm96** [moonbitlang/tree-sitter-moonbit#21]
I saw [`Copyright (c) 2023 Bao Zhiyuan`](https://github.com/moonbitlang/tree-sitter-moonbit/blob/main/LICENSE#L3) in the LICENSE file. Is this project now officially supported, or a personal project? I would be appreciate if someone could make a clarification.

**Comment by bzy-debug** [comment]
Sorry for the confusion. This was initially a personal project, but now officially supported.

We will update the license after internal discussion shortly
