### ISSUE TITLE
Broken parsing for pipe operators and access operators in newline

### ISSUE THREAD

**Issue by roife** [moonbitlang/tree-sitter-moonbit#23]
Currently the parser cannot parse source code like:

```moonbit
5   // line break
|> debug
```

```moonbit
// struct S { y: Int }
// let s: S
s   // line break
.y
```

Perhaps we should fix it in `scanner.c`? I'm not sure.

**Comment by roife** [comment]
I believe the issue with parsing multiline strings is the same as this one.

**Comment by tonyfettes** [comment]
We're looking to this issue now. We definitely need to fix `scanner.c` for the multiline string, but I'm not sure if we really need to do ASI to fix the pipeline operator (actually all binary expression) in `scanner.c`.

**Comment by tonyfettes** [comment]
The ASI is not perfect, and we don't handle multi-line string and error recovery for undelimited string, but it shall fix the example listed above.
